/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedLlmUsageRouteImport } from './routes/_authenticated/llm-usage'
import { Route as AuthenticatedEventsRouteImport } from './routes/_authenticated/events'
import { Route as AuthenticatedChatRouteImport } from './routes/_authenticated/chat'
import { Route as AuthenticatedAuditRouteImport } from './routes/_authenticated/audit'
import { Route as AuthenticatedIntegrationsIndexRouteImport } from './routes/_authenticated/integrations.index'
import { Route as AuthenticatedInstancesIndexRouteImport } from './routes/_authenticated/instances.index'
import { Route as AuthenticatedIntegrationsBlingRouteImport } from './routes/_authenticated/integrations.bling'
import { Route as AuthenticatedInstancesIdRouteImport } from './routes/_authenticated/instances.$id'
import { Route as AuthenticatedIntegrationsBlingCallbackRouteImport } from './routes/_authenticated/integrations.bling.callback'

const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedLlmUsageRoute = AuthenticatedLlmUsageRouteImport.update({
  id: '/llm-usage',
  path: '/llm-usage',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedEventsRoute = AuthenticatedEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedChatRoute = AuthenticatedChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAuditRoute = AuthenticatedAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedIntegrationsIndexRoute =
  AuthenticatedIntegrationsIndexRouteImport.update({
    id: '/integrations/',
    path: '/integrations/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedInstancesIndexRoute =
  AuthenticatedInstancesIndexRouteImport.update({
    id: '/instances/',
    path: '/instances/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedIntegrationsBlingRoute =
  AuthenticatedIntegrationsBlingRouteImport.update({
    id: '/integrations/bling',
    path: '/integrations/bling',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedInstancesIdRoute =
  AuthenticatedInstancesIdRouteImport.update({
    id: '/instances/$id',
    path: '/instances/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedIntegrationsBlingCallbackRoute =
  AuthenticatedIntegrationsBlingCallbackRouteImport.update({
    id: '/callback',
    path: '/callback',
    getParentRoute: () => AuthenticatedIntegrationsBlingRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/audit': typeof AuthenticatedAuditRoute
  '/chat': typeof AuthenticatedChatRoute
  '/events': typeof AuthenticatedEventsRoute
  '/llm-usage': typeof AuthenticatedLlmUsageRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/instances/$id': typeof AuthenticatedInstancesIdRoute
  '/integrations/bling': typeof AuthenticatedIntegrationsBlingRouteWithChildren
  '/instances/': typeof AuthenticatedInstancesIndexRoute
  '/integrations/': typeof AuthenticatedIntegrationsIndexRoute
  '/integrations/bling/callback': typeof AuthenticatedIntegrationsBlingCallbackRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/audit': typeof AuthenticatedAuditRoute
  '/chat': typeof AuthenticatedChatRoute
  '/events': typeof AuthenticatedEventsRoute
  '/llm-usage': typeof AuthenticatedLlmUsageRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/': typeof AuthenticatedIndexRoute
  '/instances/$id': typeof AuthenticatedInstancesIdRoute
  '/integrations/bling': typeof AuthenticatedIntegrationsBlingRouteWithChildren
  '/instances': typeof AuthenticatedInstancesIndexRoute
  '/integrations': typeof AuthenticatedIntegrationsIndexRoute
  '/integrations/bling/callback': typeof AuthenticatedIntegrationsBlingCallbackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/_authenticated/audit': typeof AuthenticatedAuditRoute
  '/_authenticated/chat': typeof AuthenticatedChatRoute
  '/_authenticated/events': typeof AuthenticatedEventsRoute
  '/_authenticated/llm-usage': typeof AuthenticatedLlmUsageRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/instances/$id': typeof AuthenticatedInstancesIdRoute
  '/_authenticated/integrations/bling': typeof AuthenticatedIntegrationsBlingRouteWithChildren
  '/_authenticated/instances/': typeof AuthenticatedInstancesIndexRoute
  '/_authenticated/integrations/': typeof AuthenticatedIntegrationsIndexRoute
  '/_authenticated/integrations/bling/callback': typeof AuthenticatedIntegrationsBlingCallbackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/onboarding'
    | '/audit'
    | '/chat'
    | '/events'
    | '/llm-usage'
    | '/settings'
    | '/instances/$id'
    | '/integrations/bling'
    | '/instances/'
    | '/integrations/'
    | '/integrations/bling/callback'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/onboarding'
    | '/audit'
    | '/chat'
    | '/events'
    | '/llm-usage'
    | '/settings'
    | '/'
    | '/instances/$id'
    | '/integrations/bling'
    | '/instances'
    | '/integrations'
    | '/integrations/bling/callback'
  id:
    | '__root__'
    | '/_authenticated'
    | '/login'
    | '/onboarding'
    | '/_authenticated/audit'
    | '/_authenticated/chat'
    | '/_authenticated/events'
    | '/_authenticated/llm-usage'
    | '/_authenticated/settings'
    | '/_authenticated/'
    | '/_authenticated/instances/$id'
    | '/_authenticated/integrations/bling'
    | '/_authenticated/instances/'
    | '/_authenticated/integrations/'
    | '/_authenticated/integrations/bling/callback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/llm-usage': {
      id: '/_authenticated/llm-usage'
      path: '/llm-usage'
      fullPath: '/llm-usage'
      preLoaderRoute: typeof AuthenticatedLlmUsageRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/events': {
      id: '/_authenticated/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof AuthenticatedEventsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/chat': {
      id: '/_authenticated/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof AuthenticatedChatRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/audit': {
      id: '/_authenticated/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuthenticatedAuditRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/integrations/': {
      id: '/_authenticated/integrations/'
      path: '/integrations'
      fullPath: '/integrations/'
      preLoaderRoute: typeof AuthenticatedIntegrationsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/instances/': {
      id: '/_authenticated/instances/'
      path: '/instances'
      fullPath: '/instances/'
      preLoaderRoute: typeof AuthenticatedInstancesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/integrations/bling': {
      id: '/_authenticated/integrations/bling'
      path: '/integrations/bling'
      fullPath: '/integrations/bling'
      preLoaderRoute: typeof AuthenticatedIntegrationsBlingRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/instances/$id': {
      id: '/_authenticated/instances/$id'
      path: '/instances/$id'
      fullPath: '/instances/$id'
      preLoaderRoute: typeof AuthenticatedInstancesIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/integrations/bling/callback': {
      id: '/_authenticated/integrations/bling/callback'
      path: '/callback'
      fullPath: '/integrations/bling/callback'
      preLoaderRoute: typeof AuthenticatedIntegrationsBlingCallbackRouteImport
      parentRoute: typeof AuthenticatedIntegrationsBlingRoute
    }
  }
}

interface AuthenticatedIntegrationsBlingRouteChildren {
  AuthenticatedIntegrationsBlingCallbackRoute: typeof AuthenticatedIntegrationsBlingCallbackRoute
}

const AuthenticatedIntegrationsBlingRouteChildren: AuthenticatedIntegrationsBlingRouteChildren =
  {
    AuthenticatedIntegrationsBlingCallbackRoute:
      AuthenticatedIntegrationsBlingCallbackRoute,
  }

const AuthenticatedIntegrationsBlingRouteWithChildren =
  AuthenticatedIntegrationsBlingRoute._addFileChildren(
    AuthenticatedIntegrationsBlingRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedAuditRoute: typeof AuthenticatedAuditRoute
  AuthenticatedChatRoute: typeof AuthenticatedChatRoute
  AuthenticatedEventsRoute: typeof AuthenticatedEventsRoute
  AuthenticatedLlmUsageRoute: typeof AuthenticatedLlmUsageRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedInstancesIdRoute: typeof AuthenticatedInstancesIdRoute
  AuthenticatedIntegrationsBlingRoute: typeof AuthenticatedIntegrationsBlingRouteWithChildren
  AuthenticatedInstancesIndexRoute: typeof AuthenticatedInstancesIndexRoute
  AuthenticatedIntegrationsIndexRoute: typeof AuthenticatedIntegrationsIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAuditRoute: AuthenticatedAuditRoute,
  AuthenticatedChatRoute: AuthenticatedChatRoute,
  AuthenticatedEventsRoute: AuthenticatedEventsRoute,
  AuthenticatedLlmUsageRoute: AuthenticatedLlmUsageRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedInstancesIdRoute: AuthenticatedInstancesIdRoute,
  AuthenticatedIntegrationsBlingRoute:
    AuthenticatedIntegrationsBlingRouteWithChildren,
  AuthenticatedInstancesIndexRoute: AuthenticatedInstancesIndexRoute,
  AuthenticatedIntegrationsIndexRoute: AuthenticatedIntegrationsIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
