/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as InstallRouteImport } from './routes/install'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedReportsRouteImport } from './routes/_authenticated/reports'
import { Route as AuthenticatedObservabilityRouteImport } from './routes/_authenticated/observability'
import { Route as AuthenticatedLlmUsageRouteImport } from './routes/_authenticated/llm-usage'
import { Route as AuthenticatedGoalsRouteImport } from './routes/_authenticated/goals'
import { Route as AuthenticatedEventsRouteImport } from './routes/_authenticated/events'
import { Route as AuthenticatedChatRouteImport } from './routes/_authenticated/chat'
import { Route as AuthenticatedAuditRouteImport } from './routes/_authenticated/audit'
import { Route as AuthenticatedIntegrationsIndexRouteImport } from './routes/_authenticated/integrations.index'
import { Route as AuthenticatedInstancesIndexRouteImport } from './routes/_authenticated/instances.index'
import { Route as AuthenticatedAutomationsIndexRouteImport } from './routes/_authenticated/automations.index'
import { Route as AuthenticatedSettingsWhatsappRouteImport } from './routes/_authenticated/settings_.whatsapp'
import { Route as AuthenticatedSettingsSistemaRouteImport } from './routes/_authenticated/settings_.sistema'
import { Route as AuthenticatedSettingsRulesRouteImport } from './routes/_authenticated/settings_.rules'
import { Route as AuthenticatedIntegrationsSupabaseRouteImport } from './routes/_authenticated/integrations.supabase'
import { Route as AuthenticatedIntegrationsNuvemshopRouteImport } from './routes/_authenticated/integrations.nuvemshop'
import { Route as AuthenticatedIntegrationsMercadoLivreRouteImport } from './routes/_authenticated/integrations.mercado-livre'
import { Route as AuthenticatedIntegrationsHubspotRouteImport } from './routes/_authenticated/integrations.hubspot'
import { Route as AuthenticatedIntegrationsContaazulRouteImport } from './routes/_authenticated/integrations.contaazul'
import { Route as AuthenticatedIntegrationsBlingRouteImport } from './routes/_authenticated/integrations.bling'
import { Route as AuthenticatedInstancesIdRouteImport } from './routes/_authenticated/instances.$id'
import { Route as AuthenticatedAutomationsIdRouteImport } from './routes/_authenticated/automations.$id'
import { Route as AuthenticatedIntegrationsNuvemshopCallbackRouteImport } from './routes/_authenticated/integrations.nuvemshop.callback'
import { Route as AuthenticatedIntegrationsMercadoLivreCallbackRouteImport } from './routes/_authenticated/integrations.mercado-livre.callback'
import { Route as AuthenticatedIntegrationsHubspotCallbackRouteImport } from './routes/_authenticated/integrations.hubspot.callback'
import { Route as AuthenticatedIntegrationsContaazulCallbackRouteImport } from './routes/_authenticated/integrations.contaazul.callback'
import { Route as AuthenticatedIntegrationsBlingCallbackRouteImport } from './routes/_authenticated/integrations.bling.callback'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const InstallRoute = InstallRouteImport.update({
  id: '/install',
  path: '/install',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedReportsRoute = AuthenticatedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedObservabilityRoute =
  AuthenticatedObservabilityRouteImport.update({
    id: '/observability',
    path: '/observability',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedLlmUsageRoute = AuthenticatedLlmUsageRouteImport.update({
  id: '/llm-usage',
  path: '/llm-usage',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedGoalsRoute = AuthenticatedGoalsRouteImport.update({
  id: '/goals',
  path: '/goals',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedEventsRoute = AuthenticatedEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedChatRoute = AuthenticatedChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAuditRoute = AuthenticatedAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedIntegrationsIndexRoute =
  AuthenticatedIntegrationsIndexRouteImport.update({
    id: '/integrations/',
    path: '/integrations/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedInstancesIndexRoute =
  AuthenticatedInstancesIndexRouteImport.update({
    id: '/instances/',
    path: '/instances/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAutomationsIndexRoute =
  AuthenticatedAutomationsIndexRouteImport.update({
    id: '/automations/',
    path: '/automations/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSettingsWhatsappRoute =
  AuthenticatedSettingsWhatsappRouteImport.update({
    id: '/settings_/whatsapp',
    path: '/settings/whatsapp',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSettingsSistemaRoute =
  AuthenticatedSettingsSistemaRouteImport.update({
    id: '/settings_/sistema',
    path: '/settings/sistema',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSettingsRulesRoute =
  AuthenticatedSettingsRulesRouteImport.update({
    id: '/settings_/rules',
    path: '/settings/rules',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedIntegrationsSupabaseRoute =
  AuthenticatedIntegrationsSupabaseRouteImport.update({
    id: '/integrations/supabase',
    path: '/integrations/supabase',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedIntegrationsNuvemshopRoute =
  AuthenticatedIntegrationsNuvemshopRouteImport.update({
    id: '/integrations/nuvemshop',
    path: '/integrations/nuvemshop',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedIntegrationsMercadoLivreRoute =
  AuthenticatedIntegrationsMercadoLivreRouteImport.update({
    id: '/integrations/mercado-livre',
    path: '/integrations/mercado-livre',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedIntegrationsHubspotRoute =
  AuthenticatedIntegrationsHubspotRouteImport.update({
    id: '/integrations/hubspot',
    path: '/integrations/hubspot',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedIntegrationsContaazulRoute =
  AuthenticatedIntegrationsContaazulRouteImport.update({
    id: '/integrations/contaazul',
    path: '/integrations/contaazul',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedIntegrationsBlingRoute =
  AuthenticatedIntegrationsBlingRouteImport.update({
    id: '/integrations/bling',
    path: '/integrations/bling',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedInstancesIdRoute =
  AuthenticatedInstancesIdRouteImport.update({
    id: '/instances/$id',
    path: '/instances/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAutomationsIdRoute =
  AuthenticatedAutomationsIdRouteImport.update({
    id: '/automations/$id',
    path: '/automations/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedIntegrationsNuvemshopCallbackRoute =
  AuthenticatedIntegrationsNuvemshopCallbackRouteImport.update({
    id: '/callback',
    path: '/callback',
    getParentRoute: () => AuthenticatedIntegrationsNuvemshopRoute,
  } as any)
const AuthenticatedIntegrationsMercadoLivreCallbackRoute =
  AuthenticatedIntegrationsMercadoLivreCallbackRouteImport.update({
    id: '/callback',
    path: '/callback',
    getParentRoute: () => AuthenticatedIntegrationsMercadoLivreRoute,
  } as any)
const AuthenticatedIntegrationsHubspotCallbackRoute =
  AuthenticatedIntegrationsHubspotCallbackRouteImport.update({
    id: '/callback',
    path: '/callback',
    getParentRoute: () => AuthenticatedIntegrationsHubspotRoute,
  } as any)
const AuthenticatedIntegrationsContaazulCallbackRoute =
  AuthenticatedIntegrationsContaazulCallbackRouteImport.update({
    id: '/callback',
    path: '/callback',
    getParentRoute: () => AuthenticatedIntegrationsContaazulRoute,
  } as any)
const AuthenticatedIntegrationsBlingCallbackRoute =
  AuthenticatedIntegrationsBlingCallbackRouteImport.update({
    id: '/callback',
    path: '/callback',
    getParentRoute: () => AuthenticatedIntegrationsBlingRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/install': typeof InstallRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/audit': typeof AuthenticatedAuditRoute
  '/chat': typeof AuthenticatedChatRoute
  '/events': typeof AuthenticatedEventsRoute
  '/goals': typeof AuthenticatedGoalsRoute
  '/llm-usage': typeof AuthenticatedLlmUsageRoute
  '/observability': typeof AuthenticatedObservabilityRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/automations/$id': typeof AuthenticatedAutomationsIdRoute
  '/instances/$id': typeof AuthenticatedInstancesIdRoute
  '/integrations/bling': typeof AuthenticatedIntegrationsBlingRouteWithChildren
  '/integrations/contaazul': typeof AuthenticatedIntegrationsContaazulRouteWithChildren
  '/integrations/hubspot': typeof AuthenticatedIntegrationsHubspotRouteWithChildren
  '/integrations/mercado-livre': typeof AuthenticatedIntegrationsMercadoLivreRouteWithChildren
  '/integrations/nuvemshop': typeof AuthenticatedIntegrationsNuvemshopRouteWithChildren
  '/integrations/supabase': typeof AuthenticatedIntegrationsSupabaseRoute
  '/settings/rules': typeof AuthenticatedSettingsRulesRoute
  '/settings/sistema': typeof AuthenticatedSettingsSistemaRoute
  '/settings/whatsapp': typeof AuthenticatedSettingsWhatsappRoute
  '/automations/': typeof AuthenticatedAutomationsIndexRoute
  '/instances/': typeof AuthenticatedInstancesIndexRoute
  '/integrations/': typeof AuthenticatedIntegrationsIndexRoute
  '/integrations/bling/callback': typeof AuthenticatedIntegrationsBlingCallbackRoute
  '/integrations/contaazul/callback': typeof AuthenticatedIntegrationsContaazulCallbackRoute
  '/integrations/hubspot/callback': typeof AuthenticatedIntegrationsHubspotCallbackRoute
  '/integrations/mercado-livre/callback': typeof AuthenticatedIntegrationsMercadoLivreCallbackRoute
  '/integrations/nuvemshop/callback': typeof AuthenticatedIntegrationsNuvemshopCallbackRoute
}
export interface FileRoutesByTo {
  '/install': typeof InstallRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/audit': typeof AuthenticatedAuditRoute
  '/chat': typeof AuthenticatedChatRoute
  '/events': typeof AuthenticatedEventsRoute
  '/goals': typeof AuthenticatedGoalsRoute
  '/llm-usage': typeof AuthenticatedLlmUsageRoute
  '/observability': typeof AuthenticatedObservabilityRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/': typeof AuthenticatedIndexRoute
  '/automations/$id': typeof AuthenticatedAutomationsIdRoute
  '/instances/$id': typeof AuthenticatedInstancesIdRoute
  '/integrations/bling': typeof AuthenticatedIntegrationsBlingRouteWithChildren
  '/integrations/contaazul': typeof AuthenticatedIntegrationsContaazulRouteWithChildren
  '/integrations/hubspot': typeof AuthenticatedIntegrationsHubspotRouteWithChildren
  '/integrations/mercado-livre': typeof AuthenticatedIntegrationsMercadoLivreRouteWithChildren
  '/integrations/nuvemshop': typeof AuthenticatedIntegrationsNuvemshopRouteWithChildren
  '/integrations/supabase': typeof AuthenticatedIntegrationsSupabaseRoute
  '/settings/rules': typeof AuthenticatedSettingsRulesRoute
  '/settings/sistema': typeof AuthenticatedSettingsSistemaRoute
  '/settings/whatsapp': typeof AuthenticatedSettingsWhatsappRoute
  '/automations': typeof AuthenticatedAutomationsIndexRoute
  '/instances': typeof AuthenticatedInstancesIndexRoute
  '/integrations': typeof AuthenticatedIntegrationsIndexRoute
  '/integrations/bling/callback': typeof AuthenticatedIntegrationsBlingCallbackRoute
  '/integrations/contaazul/callback': typeof AuthenticatedIntegrationsContaazulCallbackRoute
  '/integrations/hubspot/callback': typeof AuthenticatedIntegrationsHubspotCallbackRoute
  '/integrations/mercado-livre/callback': typeof AuthenticatedIntegrationsMercadoLivreCallbackRoute
  '/integrations/nuvemshop/callback': typeof AuthenticatedIntegrationsNuvemshopCallbackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/install': typeof InstallRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/audit': typeof AuthenticatedAuditRoute
  '/_authenticated/chat': typeof AuthenticatedChatRoute
  '/_authenticated/events': typeof AuthenticatedEventsRoute
  '/_authenticated/goals': typeof AuthenticatedGoalsRoute
  '/_authenticated/llm-usage': typeof AuthenticatedLlmUsageRoute
  '/_authenticated/observability': typeof AuthenticatedObservabilityRoute
  '/_authenticated/reports': typeof AuthenticatedReportsRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/automations/$id': typeof AuthenticatedAutomationsIdRoute
  '/_authenticated/instances/$id': typeof AuthenticatedInstancesIdRoute
  '/_authenticated/integrations/bling': typeof AuthenticatedIntegrationsBlingRouteWithChildren
  '/_authenticated/integrations/contaazul': typeof AuthenticatedIntegrationsContaazulRouteWithChildren
  '/_authenticated/integrations/hubspot': typeof AuthenticatedIntegrationsHubspotRouteWithChildren
  '/_authenticated/integrations/mercado-livre': typeof AuthenticatedIntegrationsMercadoLivreRouteWithChildren
  '/_authenticated/integrations/nuvemshop': typeof AuthenticatedIntegrationsNuvemshopRouteWithChildren
  '/_authenticated/integrations/supabase': typeof AuthenticatedIntegrationsSupabaseRoute
  '/_authenticated/settings_/rules': typeof AuthenticatedSettingsRulesRoute
  '/_authenticated/settings_/sistema': typeof AuthenticatedSettingsSistemaRoute
  '/_authenticated/settings_/whatsapp': typeof AuthenticatedSettingsWhatsappRoute
  '/_authenticated/automations/': typeof AuthenticatedAutomationsIndexRoute
  '/_authenticated/instances/': typeof AuthenticatedInstancesIndexRoute
  '/_authenticated/integrations/': typeof AuthenticatedIntegrationsIndexRoute
  '/_authenticated/integrations/bling/callback': typeof AuthenticatedIntegrationsBlingCallbackRoute
  '/_authenticated/integrations/contaazul/callback': typeof AuthenticatedIntegrationsContaazulCallbackRoute
  '/_authenticated/integrations/hubspot/callback': typeof AuthenticatedIntegrationsHubspotCallbackRoute
  '/_authenticated/integrations/mercado-livre/callback': typeof AuthenticatedIntegrationsMercadoLivreCallbackRoute
  '/_authenticated/integrations/nuvemshop/callback': typeof AuthenticatedIntegrationsNuvemshopCallbackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/install'
    | '/login'
    | '/onboarding'
    | '/reset-password'
    | '/audit'
    | '/chat'
    | '/events'
    | '/goals'
    | '/llm-usage'
    | '/observability'
    | '/reports'
    | '/settings'
    | '/automations/$id'
    | '/instances/$id'
    | '/integrations/bling'
    | '/integrations/contaazul'
    | '/integrations/hubspot'
    | '/integrations/mercado-livre'
    | '/integrations/nuvemshop'
    | '/integrations/supabase'
    | '/settings/rules'
    | '/settings/sistema'
    | '/settings/whatsapp'
    | '/automations/'
    | '/instances/'
    | '/integrations/'
    | '/integrations/bling/callback'
    | '/integrations/contaazul/callback'
    | '/integrations/hubspot/callback'
    | '/integrations/mercado-livre/callback'
    | '/integrations/nuvemshop/callback'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/install'
    | '/login'
    | '/onboarding'
    | '/reset-password'
    | '/audit'
    | '/chat'
    | '/events'
    | '/goals'
    | '/llm-usage'
    | '/observability'
    | '/reports'
    | '/settings'
    | '/'
    | '/automations/$id'
    | '/instances/$id'
    | '/integrations/bling'
    | '/integrations/contaazul'
    | '/integrations/hubspot'
    | '/integrations/mercado-livre'
    | '/integrations/nuvemshop'
    | '/integrations/supabase'
    | '/settings/rules'
    | '/settings/sistema'
    | '/settings/whatsapp'
    | '/automations'
    | '/instances'
    | '/integrations'
    | '/integrations/bling/callback'
    | '/integrations/contaazul/callback'
    | '/integrations/hubspot/callback'
    | '/integrations/mercado-livre/callback'
    | '/integrations/nuvemshop/callback'
  id:
    | '__root__'
    | '/_authenticated'
    | '/install'
    | '/login'
    | '/onboarding'
    | '/reset-password'
    | '/_authenticated/audit'
    | '/_authenticated/chat'
    | '/_authenticated/events'
    | '/_authenticated/goals'
    | '/_authenticated/llm-usage'
    | '/_authenticated/observability'
    | '/_authenticated/reports'
    | '/_authenticated/settings'
    | '/_authenticated/'
    | '/_authenticated/automations/$id'
    | '/_authenticated/instances/$id'
    | '/_authenticated/integrations/bling'
    | '/_authenticated/integrations/contaazul'
    | '/_authenticated/integrations/hubspot'
    | '/_authenticated/integrations/mercado-livre'
    | '/_authenticated/integrations/nuvemshop'
    | '/_authenticated/integrations/supabase'
    | '/_authenticated/settings_/rules'
    | '/_authenticated/settings_/sistema'
    | '/_authenticated/settings_/whatsapp'
    | '/_authenticated/automations/'
    | '/_authenticated/instances/'
    | '/_authenticated/integrations/'
    | '/_authenticated/integrations/bling/callback'
    | '/_authenticated/integrations/contaazul/callback'
    | '/_authenticated/integrations/hubspot/callback'
    | '/_authenticated/integrations/mercado-livre/callback'
    | '/_authenticated/integrations/nuvemshop/callback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  InstallRoute: typeof InstallRoute
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/install': {
      id: '/install'
      path: '/install'
      fullPath: '/install'
      preLoaderRoute: typeof InstallRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/reports': {
      id: '/_authenticated/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedReportsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/observability': {
      id: '/_authenticated/observability'
      path: '/observability'
      fullPath: '/observability'
      preLoaderRoute: typeof AuthenticatedObservabilityRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/llm-usage': {
      id: '/_authenticated/llm-usage'
      path: '/llm-usage'
      fullPath: '/llm-usage'
      preLoaderRoute: typeof AuthenticatedLlmUsageRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/goals': {
      id: '/_authenticated/goals'
      path: '/goals'
      fullPath: '/goals'
      preLoaderRoute: typeof AuthenticatedGoalsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/events': {
      id: '/_authenticated/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof AuthenticatedEventsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/chat': {
      id: '/_authenticated/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof AuthenticatedChatRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/audit': {
      id: '/_authenticated/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuthenticatedAuditRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/integrations/': {
      id: '/_authenticated/integrations/'
      path: '/integrations'
      fullPath: '/integrations/'
      preLoaderRoute: typeof AuthenticatedIntegrationsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/instances/': {
      id: '/_authenticated/instances/'
      path: '/instances'
      fullPath: '/instances/'
      preLoaderRoute: typeof AuthenticatedInstancesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/automations/': {
      id: '/_authenticated/automations/'
      path: '/automations'
      fullPath: '/automations/'
      preLoaderRoute: typeof AuthenticatedAutomationsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings_/whatsapp': {
      id: '/_authenticated/settings_/whatsapp'
      path: '/settings/whatsapp'
      fullPath: '/settings/whatsapp'
      preLoaderRoute: typeof AuthenticatedSettingsWhatsappRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings_/sistema': {
      id: '/_authenticated/settings_/sistema'
      path: '/settings/sistema'
      fullPath: '/settings/sistema'
      preLoaderRoute: typeof AuthenticatedSettingsSistemaRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings_/rules': {
      id: '/_authenticated/settings_/rules'
      path: '/settings/rules'
      fullPath: '/settings/rules'
      preLoaderRoute: typeof AuthenticatedSettingsRulesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/integrations/supabase': {
      id: '/_authenticated/integrations/supabase'
      path: '/integrations/supabase'
      fullPath: '/integrations/supabase'
      preLoaderRoute: typeof AuthenticatedIntegrationsSupabaseRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/integrations/nuvemshop': {
      id: '/_authenticated/integrations/nuvemshop'
      path: '/integrations/nuvemshop'
      fullPath: '/integrations/nuvemshop'
      preLoaderRoute: typeof AuthenticatedIntegrationsNuvemshopRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/integrations/mercado-livre': {
      id: '/_authenticated/integrations/mercado-livre'
      path: '/integrations/mercado-livre'
      fullPath: '/integrations/mercado-livre'
      preLoaderRoute: typeof AuthenticatedIntegrationsMercadoLivreRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/integrations/hubspot': {
      id: '/_authenticated/integrations/hubspot'
      path: '/integrations/hubspot'
      fullPath: '/integrations/hubspot'
      preLoaderRoute: typeof AuthenticatedIntegrationsHubspotRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/integrations/contaazul': {
      id: '/_authenticated/integrations/contaazul'
      path: '/integrations/contaazul'
      fullPath: '/integrations/contaazul'
      preLoaderRoute: typeof AuthenticatedIntegrationsContaazulRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/integrations/bling': {
      id: '/_authenticated/integrations/bling'
      path: '/integrations/bling'
      fullPath: '/integrations/bling'
      preLoaderRoute: typeof AuthenticatedIntegrationsBlingRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/instances/$id': {
      id: '/_authenticated/instances/$id'
      path: '/instances/$id'
      fullPath: '/instances/$id'
      preLoaderRoute: typeof AuthenticatedInstancesIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/automations/$id': {
      id: '/_authenticated/automations/$id'
      path: '/automations/$id'
      fullPath: '/automations/$id'
      preLoaderRoute: typeof AuthenticatedAutomationsIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/integrations/nuvemshop/callback': {
      id: '/_authenticated/integrations/nuvemshop/callback'
      path: '/callback'
      fullPath: '/integrations/nuvemshop/callback'
      preLoaderRoute: typeof AuthenticatedIntegrationsNuvemshopCallbackRouteImport
      parentRoute: typeof AuthenticatedIntegrationsNuvemshopRoute
    }
    '/_authenticated/integrations/mercado-livre/callback': {
      id: '/_authenticated/integrations/mercado-livre/callback'
      path: '/callback'
      fullPath: '/integrations/mercado-livre/callback'
      preLoaderRoute: typeof AuthenticatedIntegrationsMercadoLivreCallbackRouteImport
      parentRoute: typeof AuthenticatedIntegrationsMercadoLivreRoute
    }
    '/_authenticated/integrations/hubspot/callback': {
      id: '/_authenticated/integrations/hubspot/callback'
      path: '/callback'
      fullPath: '/integrations/hubspot/callback'
      preLoaderRoute: typeof AuthenticatedIntegrationsHubspotCallbackRouteImport
      parentRoute: typeof AuthenticatedIntegrationsHubspotRoute
    }
    '/_authenticated/integrations/contaazul/callback': {
      id: '/_authenticated/integrations/contaazul/callback'
      path: '/callback'
      fullPath: '/integrations/contaazul/callback'
      preLoaderRoute: typeof AuthenticatedIntegrationsContaazulCallbackRouteImport
      parentRoute: typeof AuthenticatedIntegrationsContaazulRoute
    }
    '/_authenticated/integrations/bling/callback': {
      id: '/_authenticated/integrations/bling/callback'
      path: '/callback'
      fullPath: '/integrations/bling/callback'
      preLoaderRoute: typeof AuthenticatedIntegrationsBlingCallbackRouteImport
      parentRoute: typeof AuthenticatedIntegrationsBlingRoute
    }
  }
}

interface AuthenticatedIntegrationsBlingRouteChildren {
  AuthenticatedIntegrationsBlingCallbackRoute: typeof AuthenticatedIntegrationsBlingCallbackRoute
}

const AuthenticatedIntegrationsBlingRouteChildren: AuthenticatedIntegrationsBlingRouteChildren =
  {
    AuthenticatedIntegrationsBlingCallbackRoute:
      AuthenticatedIntegrationsBlingCallbackRoute,
  }

const AuthenticatedIntegrationsBlingRouteWithChildren =
  AuthenticatedIntegrationsBlingRoute._addFileChildren(
    AuthenticatedIntegrationsBlingRouteChildren,
  )

interface AuthenticatedIntegrationsContaazulRouteChildren {
  AuthenticatedIntegrationsContaazulCallbackRoute: typeof AuthenticatedIntegrationsContaazulCallbackRoute
}

const AuthenticatedIntegrationsContaazulRouteChildren: AuthenticatedIntegrationsContaazulRouteChildren =
  {
    AuthenticatedIntegrationsContaazulCallbackRoute:
      AuthenticatedIntegrationsContaazulCallbackRoute,
  }

const AuthenticatedIntegrationsContaazulRouteWithChildren =
  AuthenticatedIntegrationsContaazulRoute._addFileChildren(
    AuthenticatedIntegrationsContaazulRouteChildren,
  )

interface AuthenticatedIntegrationsHubspotRouteChildren {
  AuthenticatedIntegrationsHubspotCallbackRoute: typeof AuthenticatedIntegrationsHubspotCallbackRoute
}

const AuthenticatedIntegrationsHubspotRouteChildren: AuthenticatedIntegrationsHubspotRouteChildren =
  {
    AuthenticatedIntegrationsHubspotCallbackRoute:
      AuthenticatedIntegrationsHubspotCallbackRoute,
  }

const AuthenticatedIntegrationsHubspotRouteWithChildren =
  AuthenticatedIntegrationsHubspotRoute._addFileChildren(
    AuthenticatedIntegrationsHubspotRouteChildren,
  )

interface AuthenticatedIntegrationsMercadoLivreRouteChildren {
  AuthenticatedIntegrationsMercadoLivreCallbackRoute: typeof AuthenticatedIntegrationsMercadoLivreCallbackRoute
}

const AuthenticatedIntegrationsMercadoLivreRouteChildren: AuthenticatedIntegrationsMercadoLivreRouteChildren =
  {
    AuthenticatedIntegrationsMercadoLivreCallbackRoute:
      AuthenticatedIntegrationsMercadoLivreCallbackRoute,
  }

const AuthenticatedIntegrationsMercadoLivreRouteWithChildren =
  AuthenticatedIntegrationsMercadoLivreRoute._addFileChildren(
    AuthenticatedIntegrationsMercadoLivreRouteChildren,
  )

interface AuthenticatedIntegrationsNuvemshopRouteChildren {
  AuthenticatedIntegrationsNuvemshopCallbackRoute: typeof AuthenticatedIntegrationsNuvemshopCallbackRoute
}

const AuthenticatedIntegrationsNuvemshopRouteChildren: AuthenticatedIntegrationsNuvemshopRouteChildren =
  {
    AuthenticatedIntegrationsNuvemshopCallbackRoute:
      AuthenticatedIntegrationsNuvemshopCallbackRoute,
  }

const AuthenticatedIntegrationsNuvemshopRouteWithChildren =
  AuthenticatedIntegrationsNuvemshopRoute._addFileChildren(
    AuthenticatedIntegrationsNuvemshopRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedAuditRoute: typeof AuthenticatedAuditRoute
  AuthenticatedChatRoute: typeof AuthenticatedChatRoute
  AuthenticatedEventsRoute: typeof AuthenticatedEventsRoute
  AuthenticatedGoalsRoute: typeof AuthenticatedGoalsRoute
  AuthenticatedLlmUsageRoute: typeof AuthenticatedLlmUsageRoute
  AuthenticatedObservabilityRoute: typeof AuthenticatedObservabilityRoute
  AuthenticatedReportsRoute: typeof AuthenticatedReportsRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedAutomationsIdRoute: typeof AuthenticatedAutomationsIdRoute
  AuthenticatedInstancesIdRoute: typeof AuthenticatedInstancesIdRoute
  AuthenticatedIntegrationsBlingRoute: typeof AuthenticatedIntegrationsBlingRouteWithChildren
  AuthenticatedIntegrationsContaazulRoute: typeof AuthenticatedIntegrationsContaazulRouteWithChildren
  AuthenticatedIntegrationsHubspotRoute: typeof AuthenticatedIntegrationsHubspotRouteWithChildren
  AuthenticatedIntegrationsMercadoLivreRoute: typeof AuthenticatedIntegrationsMercadoLivreRouteWithChildren
  AuthenticatedIntegrationsNuvemshopRoute: typeof AuthenticatedIntegrationsNuvemshopRouteWithChildren
  AuthenticatedIntegrationsSupabaseRoute: typeof AuthenticatedIntegrationsSupabaseRoute
  AuthenticatedSettingsRulesRoute: typeof AuthenticatedSettingsRulesRoute
  AuthenticatedSettingsSistemaRoute: typeof AuthenticatedSettingsSistemaRoute
  AuthenticatedSettingsWhatsappRoute: typeof AuthenticatedSettingsWhatsappRoute
  AuthenticatedAutomationsIndexRoute: typeof AuthenticatedAutomationsIndexRoute
  AuthenticatedInstancesIndexRoute: typeof AuthenticatedInstancesIndexRoute
  AuthenticatedIntegrationsIndexRoute: typeof AuthenticatedIntegrationsIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAuditRoute: AuthenticatedAuditRoute,
  AuthenticatedChatRoute: AuthenticatedChatRoute,
  AuthenticatedEventsRoute: AuthenticatedEventsRoute,
  AuthenticatedGoalsRoute: AuthenticatedGoalsRoute,
  AuthenticatedLlmUsageRoute: AuthenticatedLlmUsageRoute,
  AuthenticatedObservabilityRoute: AuthenticatedObservabilityRoute,
  AuthenticatedReportsRoute: AuthenticatedReportsRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedAutomationsIdRoute: AuthenticatedAutomationsIdRoute,
  AuthenticatedInstancesIdRoute: AuthenticatedInstancesIdRoute,
  AuthenticatedIntegrationsBlingRoute:
    AuthenticatedIntegrationsBlingRouteWithChildren,
  AuthenticatedIntegrationsContaazulRoute:
    AuthenticatedIntegrationsContaazulRouteWithChildren,
  AuthenticatedIntegrationsHubspotRoute:
    AuthenticatedIntegrationsHubspotRouteWithChildren,
  AuthenticatedIntegrationsMercadoLivreRoute:
    AuthenticatedIntegrationsMercadoLivreRouteWithChildren,
  AuthenticatedIntegrationsNuvemshopRoute:
    AuthenticatedIntegrationsNuvemshopRouteWithChildren,
  AuthenticatedIntegrationsSupabaseRoute:
    AuthenticatedIntegrationsSupabaseRoute,
  AuthenticatedSettingsRulesRoute: AuthenticatedSettingsRulesRoute,
  AuthenticatedSettingsSistemaRoute: AuthenticatedSettingsSistemaRoute,
  AuthenticatedSettingsWhatsappRoute: AuthenticatedSettingsWhatsappRoute,
  AuthenticatedAutomationsIndexRoute: AuthenticatedAutomationsIndexRoute,
  AuthenticatedInstancesIndexRoute: AuthenticatedInstancesIndexRoute,
  AuthenticatedIntegrationsIndexRoute: AuthenticatedIntegrationsIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  InstallRoute: InstallRoute,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
